import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Flat config as generated by create-next-app for Next.js 16. The earlier
// FlatCompat setup crashed with a circular-structure error on this version.
export default defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([".next/**", "node_modules/**", "drizzle/**", "next-env.d.ts"]),
]);
